### ISSUE TITLE
Attaching current datetime to email subject

### ISSUE THREAD

**Issue by stphnlwlsh** [datalust/seq-app-digestemail#9]
Not quite sure how to implement this, but Gmail is making it very difficult by threading each email that comes out of the digest. I'd like to attach a datetime stamp to each subject, but can't quite figure out how to do that.

Anything out of the box with .NET handlebars that would accomplish this?

**Comment by nblumhardt** [comment]
Hi! Not tried, but, `{{$Events.[0].$UtcTimestamp}}` might do the trick? HTH!

**Comment by stphnlwlsh** [comment]
Missed your comment @nblumhardt. I'll give it a go tomorrow!

**Comment by stphnlwlsh** [comment]
@nblumhardt tried this out, but couldn't get it to work. I went a different direction on this and started using dashboard alerts instead which seem to work for us.
